### ISSUE TITLE
Approriate Failure Reason.

### ISSUE THREAD

**Issue by Abhishek-90** [rowyio/rowy#1378] opened 2023-08-10 09:34 UTC
**Describe the bug**
I faced an issue while creating a new firebase project from Rowy. The issue was that my firebase `authToken` expired. But it was initially unclear to me because this reason was not visible to me unless I opened the console to check for logs. An error box appeared in the bottom left corner but it didn't display any message(check attached screenshot). If the message box displayed the reason it would be better rather than opening console.

It can be a `good first issue` and I would like to take it up.

**Expected behavior**
The error box(in bottom-left) to display appropriate error message.

**Screenshots**

![Screenshot_1](https://github.com/rowyio/rowy/assets/43419831/c424a79c-3374-43f1-a35a-1632db5fd9f9)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Abhishek-90** [comment] 2023-08-10 15:02
Can I take this issue?

**Comment by harinij** [comment] 2023-09-07 03:01
Hi @Abhishek-90 - this needs a bit of investigation to ensure this is a frontend issue vs backend.

cc @il3ven who will be looking into this adding comments.

**Comment by il3ven** [comment] 2023-09-07 10:59
@Abhishek-90 How can I reproduce this? From where does it originate? I think firebase handles refreshing of tokens so we shouldn't see this error in the wild. Anyway, if it is reproducible we can add an error message.

**Comment by il3ven** [comment] 2023-09-14 14:45
@Abhishek-90 Thanks for reporting this. I was able to find the reason and replicate it. It has been fixed internally.

**Closed by il3ven** 2023-09-14 14:45 UTC
Labels: under-investigation
