### ISSUE TITLE
reference field not displaying content 

### ISSUE THREAD

**Issue by padeepz** [rowyio/rowy#667] opened 2022-03-15 11:29 UTC
**Describe the bug**
when there is a reference field in a document, it is not displaying

**Comment by notsidney** [comment] 2022-03-16 03:57
Hello, we don’t currently have a [field type](https://docs.rowy.io/field-types/supported-fields) that supports the Firestore references. We’re looking into how we can support this.

**Comment by notsidney** [comment] 2022-03-16 03:59
Duplicate of #534

**Closed** 2022-06-17 04:32 UTC
Labels: enhancement
