### ISSUE TITLE
Notification showing on each click event 

### ISSUE THREAD

**Issue by santoshgistto** [rowyio/rowy#669] opened 2022-03-21 03:23 UTC
Rowy run setup notification showing on each click event 
<img width="361" alt="Screen Shot 2022-03-20 at 11 18 50 PM" src="https://user-images.githubusercontent.com/12577046/159201018-75e24b23-dcf9-493c-b411-2cec2a9bd3bd.png">
**To Reproduce**
1. Don't setup rowy run 
2. Run application `npm start`
3. click on menu items to multiple pages

**Expected behavior**
Would be good if we show only per session and with close action icon.

**Comment by shamsmosowi** [comment] 2022-03-21 04:00
which version are you on? it should be fixed on v2.4

**Comment by santoshgistto** [comment] 2022-03-23 04:12
i Have pulled main branch

**Comment by notsidney** [comment] 2022-03-28 05:29
Hi @santoshgistto, I cannot reproduce this issue. Could you please check that the version you’re running is v2.4.0 or later in Project Settings? http://localhost:3000/settings/project

**Comment by santoshgistto** [comment] 2022-03-28 18:51
@notsidney  yes it is `"version": "2.4.0",`

**Comment by notsidney** [comment] 2022-03-30 23:15
Hi @santoshgistto, the code that displays that snackbar was removed in commit cf10f9c and was released as part of v2.4.0. There is no other code that would display this snackbar.

I think what’s happening is that while you’ve pulled from the main branch, so your local clone is up to date at v2.4.0, your deployment of the web app is still running the previous version.

This is why I asked you to verify the version in the Project Settings page on the web app, and not the package.json value.

You need to re-deploy the app to your webhost or if you’re running a localhost dev server, restart it.

**Comment by santoshgistto** [comment] 2022-03-31 18:11
@notsidney  i have tried to reproduce but unfortunately app crashing with the following error 
```
Failed to compile.

/react/rowy/src/components/TableHeader/CloudLogs/BuildLogs/index.tsx
TypeScript error in 
/react/rowy/src/components/TableHeader/CloudLogs/BuildLogs/index.tsx(136,24):
Property 'push' does not exist on type 'ReactNodeArray'.  TS2339
    134 | 
    135 |     if (diff !== prevDiff) {
  > 136 |       renderedLogItems.push(
        |                        ^
    137 |         <CloudLogSubheader key={`${diff} days ago`}>
    138 |           {diff === 0 ? "Today" : diff === 1 ? "Yesterday" : `${diff} days ago`}
    139 |         </CloudLogSubheader>
```
after taking update `git pull`

**Comment by notsidney** [comment] 2022-03-31 23:43
It looks like an issue with the node modules installed in your local clone.

Try reinstalling dependencies using `rm -rf node_modules; yarn` then rebuilding.

If that doesn’t work, make a new clone of the repo.

**Closed** 2022-10-13 06:07 UTC
Labels: bug
