### ISSUE TITLE
Error: Rowy API fail /firebaseToken?projectId=preplaced-prod: 500

### ISSUE THREAD

**Issue by Shailesh248** [rowyio/rowy#833] opened 2022-09-21 05:56 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Rowy Run version**
If applicable, share the Rowy Run version from your project settings.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wzulfikar** [comment] 2022-09-27 12:05
This issue has incomplete info (similar to #841) and possibly a duplicate of #843.

**Comment by notsidney** [comment] 2022-10-11 02:47
Thanks, this issue has been fixed.

**Closed by notsidney** 2022-10-11 02:47 UTC
